{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "5b88ca09",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import cdx_toolkit\n",
    "import os\n",
    "import multiprocessing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "bc57de19",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Year:2006, Total Extracted:0, Total Unique: 0\n",
      "Year:2007, Total Extracted:0, Total Unique: 0\n",
      "Year:2008, Total Extracted:27804, Total Unique: 27717\n",
      "Year:2009, Total Extracted:188096, Total Unique: 106775\n",
      "Year:2010, Total Extracted:4686, Total Unique: 4182\n",
      "Year:2011, Total Extracted:882, Total Unique: 817\n",
      "Year:2012, Total Extracted:10205, Total Unique: 7614\n",
      "Year:2013, Total Extracted:1200, Total Unique: 559\n",
      "Year:2014, Total Extracted:7567, Total Unique: 5772\n",
      "Year:2015, Total Extracted:2, Total Unique: 2\n",
      "Year:2016, Total Extracted:0, Total Unique: 0\n"
     ]
    }
   ],
   "source": [
    "cdx = cdx_toolkit.CDXFetcher(source='cc')\n",
    "url = 'https://www.linkedin.com/in/*'\n",
    "\n",
    "for year in np.arange(2006, 2017, 1):\n",
    "    lim = 1000000\n",
    "    objs = list(cdx.iter(url, from_ts=f'{year}01', to=f'{year+1}01', limit = lim, filter='=status:200'))\n",
    "    \n",
    "    print(f\"Year:{year}, Total Extracted:{len(objs)}, Total Unique: {len(set([objs[i]['urlkey'] for i in range(len(objs))]))}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "abfe734b",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 5 µs, sys: 5 µs, total: 10 µs\n",
      "Wall time: 22.4 µs\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "11 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f279cfbbf10>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "12 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb613710>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "13 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfe6550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "14 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb613510>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "15 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af0650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "16 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfe0d10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "17 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af6310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "18 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb47c950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "19 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26518aced0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "20 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbb850>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "21 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f279cfbb710>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "22 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26517fd290>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "23 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650b28950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "24 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2650af64d0>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "25 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af06d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "26 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2651234210>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "27 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f26fb613d50>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "28 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f279cfe6250>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "29 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f26fb613d90>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "30 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f26512131d0>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "31 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af0690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "32 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af6490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "33 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26517fdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "34 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb47c690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "35 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbb590>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "36 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbb710>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "37 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26518ac750>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "38 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650b282d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "39 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af64d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "40 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af0f10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "41 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2651735f10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "42 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb613510>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "43 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f279cfe6790>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "44 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2651234bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "45 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af0910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "46 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af64d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "47 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f26517fd850>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "48 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb47c310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "49 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbb310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "50 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfe69d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "51 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbb6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "52 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb47c310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "53 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26517fdf50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "54 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af62d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "55 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af0b90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "56 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2651234410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "57 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb613e90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "58 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f279cfd7690>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "59 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f279cfe0f90>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "60 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af0850>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "61 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650af6090>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "62 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26517fd150>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "63 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f26fb47cf50>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "64 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbbcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "65 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfd7310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "66 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f279cfbbc50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "67 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fb47c390>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "68 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26517f92d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "69 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2650b28e10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "70 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2650af6290>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "71 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2650af0a10>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "72 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f26fb6137d0>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "73 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2651234c50>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n",
      "74 failures for url https://web.archive.org/cdx/search/cdx {'to': '200701', 'limit': 1000000, 'filter': ['statuscode:200'], 'url': 'https://www.linkedin.com/in/*', 'output': 'json', 'page': 0, 'from': '200601'}: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /cdx/search/cdx?to=200701&limit=1000000&filter=statuscode%3A200&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2F%2A&output=json&page=0&from=200601 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2650af6050>, 'Connection to web.archive.org timed out. (connect timeout=30.0)'))\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-56-8f1d3ace3b9c>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      6\u001b[0m         \u001b[0;32mpass\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m     \u001b[0mlim\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m1000000\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m     \u001b[0mobjs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlist\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcdx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0miter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfrom_ts\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34mf'{year}01'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mto\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34mf'{year+1}01'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlimit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlim\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfilter\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'status:200'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      9\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"Obtained {year}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m     \u001b[0mstorlist\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/cdx_toolkit/__init__.py\u001b[0m in \u001b[0;36miter\u001b[0;34m(self, url, **kwargs)\u001b[0m\n\u001b[1;32m    282\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    283\u001b[0m         \u001b[0mindex_list\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcustomize_index_list\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 284\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mCDXFetcherIter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mindex_list\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mindex_list\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    285\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    286\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mitems\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pragma: no cover\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/cdx_toolkit/__init__.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, cdxfetcher, params, index_list)\u001b[0m\n\u001b[1;32m    163\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mindex_list\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mindex_list\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    164\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 165\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_more\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    166\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    167\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mget_more\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/cdx_toolkit/__init__.py\u001b[0m in \u001b[0;36mget_more\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    173\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    174\u001b[0m             status, objs = self.cdxfetcher.get_for_iter(self.endpoint, self.page,\n\u001b[0;32m--> 175\u001b[0;31m                                                         params=self.params, index_list=self.index_list)\n\u001b[0m\u001b[1;32m    176\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'last endpoint'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    177\u001b[0m                 \u001b[0mLOGGER\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'get_more: I have reached the end'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/cdx_toolkit/__init__.py\u001b[0m in \u001b[0;36mget_for_iter\u001b[0;34m(self, endpoint, page, params, index_list)\u001b[0m\n\u001b[1;32m    302\u001b[0m         \u001b[0mendpoint\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mindex_list\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mendpoint\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    303\u001b[0m         \u001b[0mparams\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'page'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpage\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 304\u001b[0;31m         \u001b[0mresp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmyrequests_get\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mendpoint\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcdx\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    305\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mresp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstatus_code\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m400\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pywb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    306\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0;34m'last page'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/cdx_toolkit/myrequests.py\u001b[0m in \u001b[0;36mmyrequests_get\u001b[0;34m(url, params, headers, cdx, allow404)\u001b[0m\n\u001b[1;32m     45\u001b[0m             \u001b[0mLOGGER\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'getting %s %r'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     46\u001b[0m             resp = requests.get(url, params=params, headers=headers,\n\u001b[0;32m---> 47\u001b[0;31m                                 timeout=(30., 30.), allow_redirects=False)\n\u001b[0m\u001b[1;32m     48\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mcdx\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mresp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstatus_code\u001b[0m \u001b[0;32min\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;36m400\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m404\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     49\u001b[0m                 \u001b[0;31m# 400: ia html error page -- probably page= is too big -- not an error\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/requests/api.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     71\u001b[0m     \"\"\"\n\u001b[1;32m     72\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 73\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"get\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     74\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     75\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/requests/api.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     57\u001b[0m     \u001b[0;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     58\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 59\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     60\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     61\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    585\u001b[0m         }\n\u001b[1;32m    586\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 587\u001b[0;31m         \u001b[0mresp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    588\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    589\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    699\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    700\u001b[0m         \u001b[0;31m# Send the request\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 701\u001b[0;31m         \u001b[0mr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    702\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    703\u001b[0m         \u001b[0;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    497\u001b[0m                     \u001b[0mdecode_content\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    498\u001b[0m                     \u001b[0mretries\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmax_retries\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 499\u001b[0;31m                     \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    500\u001b[0m                 )\n\u001b[1;32m    501\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    708\u001b[0m                 \u001b[0mbody\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbody\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    709\u001b[0m                 \u001b[0mheaders\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 710\u001b[0;31m                 \u001b[0mchunked\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mchunked\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    711\u001b[0m             )\n\u001b[1;32m    712\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    384\u001b[0m         \u001b[0;31m# Trigger any extra validation we need to do.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    385\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 386\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_validate_conn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    387\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    388\u001b[0m             \u001b[0;31m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m   1038\u001b[0m         \u001b[0;31m# Force connect early to allow us to validate the connection.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1039\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"sock\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# AppEngine might not have  `.sock`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1040\u001b[0;31m             \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1041\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1042\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_verified\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/urllib3/connection.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    356\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    357\u001b[0m         \u001b[0;31m# Add certificate verification\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 358\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msock\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_new_conn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    359\u001b[0m         \u001b[0mhostname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    360\u001b[0m         \u001b[0mtls_in_tls\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/urllib3/connection.py\u001b[0m in \u001b[0;36m_new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    173\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    174\u001b[0m             conn = connection.create_connection(\n\u001b[0;32m--> 175\u001b[0;31m                 \u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_dns_host\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mport\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mextra_kw\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    176\u001b[0m             )\n\u001b[1;32m    177\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/chrisliao/.local/lib/python3.7/site-packages/urllib3/util/connection.py\u001b[0m in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[1;32m     83\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0msource_address\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     84\u001b[0m                 \u001b[0msock\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbind\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msource_address\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 85\u001b[0;31m             \u001b[0msock\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msa\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     86\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0msock\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     87\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "for year in np.arange(2006, 2017, 1):\n",
    "    %%time\n",
    "    try:\n",
    "        os.mkdir(\"cc/\"+str(year))\n",
    "    except:\n",
    "        pass\n",
    "    lim = 1000000\n",
    "    objs = list(cdx.iter(url, from_ts=f'{year}01', to=f'{year+1}01', limit = lim, filter='status:200'))\n",
    "    print(f\"Obtained {year}\")\n",
    "    storlist = []\n",
    "    j = 0\n",
    "    def outputPersonIA(objs):\n",
    "        global j\n",
    "        global storlist\n",
    "        if objs['urlkey'] not in storlist:\n",
    "            # Creating an HTML file\n",
    "            Func = open(f\"cc/test/Person{j+1}.html\",\"w\")\n",
    "            # Adding input data to the HTML file\n",
    "            try:\n",
    "                Func.write(objs.content.decode(\"utf-8\"))\n",
    "                j+=1\n",
    "            except:\n",
    "                pass\n",
    "                #print(f\"Failed saving {objs[i]['urlkey']}\")\n",
    "            Func.close()\n",
    "            storlist.append(objs['urlkey'])\n",
    "\n",
    "    pool = multiprocessing.Pool(8)\n",
    "    pool.map(outputPersonIA, objs)\n",
    "    \n",
    "    print(storlist)\n",
    "    \n",
    "    directory = f\"cc/{year}\"\n",
    "    print(f\"Finished {year}, Total saved: {len(os.listdir(directory))}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
